//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BibliotheekApp
{
    using System;
    using System.Collections.Generic;

    public partial class Boeken
    {
        public int Id { get; set; }
        public string Titel { get; set; }
        public Nullable<int> AantalPaginas { get; set; }
        public Nullable<int> Score { get; set; }
        public string Publicatie { get; set; }
        public Nullable<int> UitgeverId { get; set; }

        public override string ToString()
        {
            return Titel;
        }
    }
}
