//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BibliotheekApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class BoekenGenres
    {
        public int Id { get; set; }
        public Nullable<int> BoekId { get; set; }
        public Nullable<int> GenreId { get; set; }

        public BoekenGenres()
        {

        }

        public BoekenGenres(int boekId, int genreId)
        {
            this.BoekId = boekId;
            this.GenreId = genreId;
        }
    }
}
