//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BibliotheekApp
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BoekenDBEntities : DbContext
    {
        public BoekenDBEntities()
            : base("name=BoekenDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Auteurs> Auteurs { get; set; }
        public virtual DbSet<Boeken> Boeken { get; set; }
        public virtual DbSet<BoekenAuteurs> BoekenAuteurs { get; set; }
        public virtual DbSet<BoekenGenres> BoekenGenres { get; set; }
        public virtual DbSet<Genres> Genres { get; set; }
        public virtual DbSet<Uitgeverijen> Uitgeverijen { get; set; }
    }
}
